# DO NOT REMOVE THIS
theme = "codex" 

# Override these settings with your own
title = "Code Review (Test)"
languageCode = "en-us"
baseURL = "/"
copyright = "© 2020"

# Add your Disqus shortname here.
# disqusShortname = ""

# Add your Google Analytics identifier: UA-XXXXXXXX-X
# googleAnalytics = "" 

# Optional params
[params]
  # Follow the Hugo date/time format reference here: 
  # https://gohugo.io/functions/format/#gos-layout-string
  dateFormat = "Jan 2 2006"

  podcastURL = "https://code-review-podcast.s3.us-east-2.amazonaws.com/"

  # Links to your social accounts, comment/uncomment as needed. Icons will be displayed for those specified.

  github = "https://github.com/nadirabid"
  apple = "https://podcasts.apple.com/us/podcast/code-review/id1528099679"
  spotify = "https://open.spotify.com/show/3fbDJ4lJSQwXMcwpnE3G55"
  stitcher = "https://www.stitcher.com/podcast/code-review?refid=stpr"
  google = "https://podcasts.google.com/feed/aHR0cDovL25hZGlyYWJpZC5naXRodWIuaW8vaW5kZXgueG1s"

  # email = "mailto:<your email>"
  # facebook = "https://facebook.com/<your handle>"
  # gitlab = "https://gitlab.com/<your handle>"
  # instagram = "https://instagram.com/<your handle>"
  # linkedin = "<link to your profile>"
  # youtube = "https://www.youtube.com/channel/<your channel>"
  
  # Titles for your icons (shown as tooltips), and also their display order.
  # Currently, these icons are supported: 
  #   "Twitter", "GitHub", "Email", "Facebook", "GitLab", "Instagram", "LinkedIn", "YouTube"
  iconOrder = ["Apple", "Spotify", "Google", "Stitcher"]

  # Metadata for Twitter cards, defaults to params.twitter
  # twitterSite = "@<your handle>"
  # twitterAuthor = "@<your handle>"

  # Set to true to display page title in table of contents in blog posts.
  showPageTitleInTOC = false

# This disables Hugo's default syntax highlighting in favor
# of prismjs. If you wish to use Hugo's default syntax highlighting
# over prismjs, remove this. You will also need to remove the prismjs
# vendor script in layouts/blog/single.html.
[markup]
  [markup.highlight]
    codeFences = false
    
  # Set to false to disallow raw HTML in markdown files
  [markup.goldmark.renderer]
      unsafe = true

# Controls the navigation
[[menu.main]]
  identifier = "about"
  name = "about"
  title = "About"
  url = "/"

[[menu.main]]
  identifier = "podcasts"
  name = "podcasts"
  title = "podcasts"
  url = "/posts"
